twitter:
  api:
    url: "https://api.twitter.com/2/tweets/search/recent"
    bearer-token: "AAAAAAAAAAAAAAAAAAAAAJTI4AEAAAAAaHoCJJsVxSD%2FNJhBMLupTX7z3q0%3DQvv2OyaK6INxVRNsgHAUTFssqORtvHtxyaYIA3orPHMRxLKgzr"
#AAAAAAAAAAAAAAAAAAAAAAw7zgEAAAAA0UZzd3aFwNudlzGJRKRQnC60fuQ%3DBNsBZ1czdCqp71p5T6eRAlT0TgT8PFXB2ryMEDnOPglts9rw18